### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by masaya-men** [masaya-men/protospace-34863#1]
## URL
https://protospace-34863.herokuapp.com/

**Comment by nishi418** [comment]
masaya-menさん
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

別途、最終課題の案内をチャンネルの方に送信させて頂きます。
今しばらくお待ちください。
